version: "3.7"
services:
  api:
    container_name: ep-api
    build:
      context: ./backend/
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    ports:
      - 8081:5000
    env_file:
      - ./backend/.backend.env
    volumes:
      - ep_files:/home/appuser/app/files
      - ./backend/instance:/home/appuser/app/instance
  app:
    container_name: eclecticpickup-app
    restart: unless-stopped
    build:
      context: ./frontend/
      dockerfile: Dockerfile.frontend
    ports:
      - 3001:80
    depends_on:
      - api
volumes:
  ep_files: