version: "3.7"
services:
  api:
    container_name: tafweb-api
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - 8080:8080
  app:
    container_name: tafweb-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:80
    depends_on:
      - api